version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: retention_postgres
    environment:
      POSTGRES_DB: retention_db
      POSTGRES_USER: retention_user
      POSTGRES_PASSWORD: retention_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - retention_network

  redis:
    image: redis:7-alpine
    container_name: retention_redis
    ports:
      - "6379:6379"
    networks:
      - retention_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: retention_backend
    environment:
      DATABASE_URL: postgresql://retention_user:retention_pass@postgres:5432/retention_db
      REDIS_URL: redis://redis:6379
      SECRET_KEY: your-secret-key-change-in-production
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app
    networks:
      - retention_network
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload

  celery:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: retention_celery
    environment:
      DATABASE_URL: postgresql://retention_user:retention_pass@postgres:5432/retention_db
      REDIS_URL: redis://redis:6379
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app
    networks:
      - retention_network
    command: celery -A app.celery_app worker --loglevel=info

  celery-beat:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: retention_celery_beat
    environment:
      DATABASE_URL: postgresql://retention_user:retention_pass@postgres:5432/retention_db
      REDIS_URL: redis://redis:6379
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app
    networks:
      - retention_network
    command: celery -A app.celery_app beat --loglevel=info

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: retention_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - retention_network
    command: npm run dev

volumes:
  postgres_data:

networks:
  retention_network:
    driver: bridge